name: Check frontend workflow

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout front repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build